spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /console
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3316/groubing?serverTimezone=Asia/Seoul
#    username: root
#    password: 1234
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:groubing
    username: sa
    password:
