spring:
  jpa:
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
