spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /console
  sql:
    init:
      dataLocations: classpath:data-local.sql
      mode: embedded
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:groubing
    username: sa
    password:
