= GROUBING REST API Docs
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[introduction]]
== 소개

Groubing 서비스 Backend API 문서

* link:overview.html[개요,window=_blank]
* link:common.html[공통사항,window=_blank]

[[member]]
== 회원

회원 도메인과 관련된 API 입니다.

[[member-login]]
=== 로그인 API

* link:member/LoginApi.html[로그인 API,window=_blank]

[[member-signup]]
=== 회원가입 API

* link:member/SignUp.html[회원가입 API,window=_blank]

[[bingo]]
== 빙고

빙고 도메인과 관련된 API 입니다.

=== 빙고 기본 정보

* link:bingo/BingoInfo.html[빙고 기본정보,window=_blank]

[[bingo-create]]
=== 빙고 생성

operation::create-bingo[snippets='http-request,request-fields,http-response,response-fields']

[[bingo-find]]
=== 빙고 조회

operation::bingo-board-find[snippets='http-request,http-response,response-fields']

[[edit-bingo-board]]
=== 빙고 보드 수정

[[edit-bingo-board-default]]
==== 제목 및 목표수 수정

빙고 보드에 대한 내용을 수정합니다.
수정 가능한 요소는 다음과 같습니다.

- 제목
- 목표수

operation::edit-bingo-board[snippets='http-request,request-fields']

[[edit-bingo-board-memo]]
==== 메모 수정

빙고 보드의 메모를 수정합니다.

operation::edit-bingo-board-memo[snippets='http-request,request-fields']

[[edit-bingo-board-open]]
==== 공개여부 수정

빙고 보드의 공개여부를 수정합니다.

operation::edit-bingo-board-open[snippets='http-request,request-fields']

[[edit-bingo-board-response-fields]]
==== 빙고 보드 수정 공통 응답 모델

각 빙고 보드 수정 API 의 응답 모델은 다음과 같습니다.

operation::edit-bingo-board[snippets='response-fields']

[[edit-bingo-item]]
=== 빙고 아이템 수정

operation::edit-bingo-item[snippets='http-request,request-fields,http-response,response-fields']
